=== carlosdelfino/ALF/cnf/topologia.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.2 U (http://www.xmlspy.com) by Aminadabe (Aminadabe) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Topologia">
		<xs:annotation>
			<xs:documentation>Elemento XML Raiz que monta a topologia para os testes</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Temos aqui sequencias de elementos e Canais</xs:documentation>
				</xs:annotation>
				<xs:element ref="Elemento" maxOccurs="unbounded"/>
				<xs:element ref="Canal" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Elemento">
		<xs:annotation>
			<xs:documentation>Descrevemos os elementos que iremos ter formando os canais</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="id" type="xs:ID" use="required"/>
			<xs:attribute name="tipo" type="xs:string" use="required"/>
			<xs:attribute name="nome" type="xs:string"/>
			<xs:attribute name="ccw" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Canal">
		<xs:annotation>
			<xs:documentation>Descrevemos um canal da topologia. Este canal é composto por elementos</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:annotation>
					<xs:documentation>Temos uma seguencia de elementos, veja que estes elementos são apenas referencia ao tipo Elemento.</xs:documentation>
				</xs:annotation>
				<xs:element ref="Elementos" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Elementos que compõem a rede, este campo é apenas uma referencia ao ID do elemento, evitando assim que tenhamos redundancia de dados.</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:ID"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="nome" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Elementos">
		<xs:annotation>
			<xs:documentation>Elementos que compoem o canal, este elemento xml tem como attributo o ID do Elemento do tipo Nó.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="idElemento"/>
			<xs:attribute name="sentido"/>
		</xs:complexType>
	</xs:element>
	<xs:attribute name="tipo" type="xs:string">
		<xs:annotation>
			<xs:documentation>Faz referencia ao ID dos componentes que forão definidos no arquivo Biblioteca</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:attribute name="nome" type="xs:string">
		<xs:annotation>
			<xs:documentation>Nome do elemento ou canal</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:attribute name="idElemento"/>
	<xs:attribute name="id">
		<xs:annotation>
			<xs:documentation>Identificação do elemento da rede ou do canal, veja a anotação abaixo(**).</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:ID">
				<xs:whiteSpace value="collapse"/>
				<xs:minLength value="2"/>
				<xs:maxLength value="3"/>
				<xs:pattern value="\p{Nd}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="ccw" type="xs:boolean">
		<xs:annotation>
			<xs:documentation>Indica o Sentido que o link irá ligar os nós, se verdadeiro é counter clock wise, ou seja no sentido ante horariro.</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:annotation>
		<xs:documentation>**O id quando usado em elemento de rede que seja fibra, deve ser composto por uma letra f (minuscula) e os numeros que compõem o ID do Nó sem a Letra "n" (que siginifica n), portanto, se estou identificando a Fibra que liga o Nó 20 ao nó 35, a identificação da fibra será f2035, se a ouver ligação CCW (Counter Clock Wise)  relevante deve ser também criada a Fibra F3520, um detalhe importante, o proprio algoritimo pode deduzir isto automaticamente.</xs:documentation>
	</xs:annotation>
</xs:schema>

=== carlosdelfino/ALF/cnf/topologia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.2 U (http://www.xmlspy.com) by Aminadabe (Aminadabe) -->
<Topologia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Eclipse\workspace\Correlação de Alarmes\cnf\topologia.xsd" xsi:biblioteca="C:\Eclipse\workspace\Correlação de Alarmes\cnf\biblioteca.xsd">
	<Elemento id="n01" tipo="nl" nome="No de Rede 1"/>
	<Elemento id="n02" tipo="nc" nome="No de Rede 2"/>
	<Elemento id="n03" tipo="nc" nome="No de Rede 3"/>
	<Elemento id="n04" tipo="nl" nome="No de Rede 4"/>
	<Elemento id="n05" tipo="nl" nome="No de Rede 5"/>
	<Elemento id="n06" tipo="nc" nome="No de Rede 6"/>
	<Elemento id="n07" tipo="nl" nome="No de Rede 7"/>
	<Elemento id="n08" tipo="nc" nome="No de Rede 8"/>
	<Elemento id="n09" tipo="nl" nome="No de Rede 9"/>
	<Elemento id="n10" tipo="nl" nome="No de Rede 10"/>
	<Elemento id="n11" tipo="nl" nome="No de Rede 11"/>
	<Elemento id="n12" tipo="nl" nome="No de Rede 12"/>
	<Elemento id="n13" tipo="nc" nome="No de Rede 13"/>
	<Elemento id="n14" tipo="nl" nome="No de Rede 14"/>
	<Elemento id="n15" tipo="nc" nome="No de Rede 15"/>
	<Elemento id="n16" tipo="nc" nome="No de Rede 16"/>
	<Elemento id="n17" tipo="nl" nome="No de Rede 17"/>
	<Elemento id="n18" tipo="nl" nome="No de Rede 18"/>
	<Elemento id="n19" tipo="nl" nome="No de Rede 19"/>
	<Elemento id="n20" tipo="nl" nome="Nó de Rede 20 - Salvador"/>
	<Elemento id="n21" tipo="nl" nome="Nó de Rede 21"/>
	<Elemento id="f0103" tipo="fibra" nome="Fibra entre No 01 e 03" ccw="true"/>
	<Elemento id="f0208" tipo="fibra" nome="Fibra entre No 02 e 08" ccw="false"/>
	<Elemento id="f0810" tipo="fibra" nome="Fibra entre Nó 08 e 10" ccw="false"/>
	<Elemento id="f1015" tipo="fibra" ccw="false"/>
	<Elemento id="f1516" tipo="fibra" ccw="false"/>
	<Elemento id="f1618" tipo="fibra"/>
	<Elemento id="f1213" tipo="fibra"/>
	<Elemento id="f1314" tipo="fibra" ccw="false"/>
	<Elemento id="f1415" tipo="fibra" ccw="false"/>
	<Elemento id="f1820" tipo="fibra"/>
	<Elemento id="f0306" tipo="fibra"/>
	<Elemento id="f0611" tipo="fibra"/>
	<Elemento id="f1116" tipo="fibra"/>
	<Elemento id="f2021" tipo="fibra"/>
	<Elemento id="f0102" tipo="fibra"/>
	<Elemento id="f0809" tipo="fibra"/>
	<Elemento id="f0912" tipo="fibra"/>
	<Elemento id="f1615" tipo="fibra" ccw="true"/>
	<Elemento id="f1514" tipo="fibra" ccw="true"/>
	<Elemento id="f1413" tipo="fibra" ccw="true"/>
	<Elemento id="f1317" tipo="fibra"/>
	<Canal id="c1" nome="Canal 1">
		<Elementos idElemento="n02"/>
		<Elementos idElemento="n08"/>
		<Elementos idElemento="n10"/>
		<Elementos idElemento="n15"/>
		<Elementos idElemento="n16"/>
		<Elementos idElemento="n18"/>
	</Canal>
	<Canal id="c2" nome="Canal 2">
		<Elementos idElemento="n12"/>
		<Elementos idElemento="n13"/>
		<Elementos idElemento="n14"/>
		<Elementos idElemento="n15"/>
		<Elementos idElemento="n16"/>
		<Elementos idElemento="n18"/>
		<Elementos idElemento="n20"/>
	</Canal>
	<Canal id="c3" nome="Canal 3">
		<Elementos idElemento="n03"/>
		<Elementos idElemento="n06"/>
		<Elementos idElemento="n11"/>
		<Elementos idElemento="n16"/>
		<Elementos idElemento="n18"/>
		<Elementos idElemento="n20"/>
		<Elementos idElemento="n21"/>
	</Canal>
	<Canal id="c4" nome="Canal 4">
		<Elementos idElemento="n01"/>
		<Elementos idElemento="n02"/>
		<Elementos idElemento="n08"/>
		<Elementos idElemento="n09"/>
		<Elementos idElemento="n12"/>
		<Elementos idElemento="n13"/>
		<Elementos idElemento="n14"/>
	</Canal>
	<Canal id="c5" nome="Canal 5">
		<Elementos idElemento="n08"/>
		<Elementos idElemento="n10"/>
		<Elementos idElemento="n11"/>
	</Canal>
	<Canal id="c6" nome="Canal 6">
		<Elementos idElemento="n11"/>
		<Elementos idElemento="n16"/>
		<Elementos idElemento="n15"/>
		<Elementos idElemento="n14" sentido="ccw"/>
		<Elementos idElemento="n13"/>
		<Elementos idElemento="n17"/>
	</Canal>
</Topologia>
